language: ruby
rvm:
  - 2.3.1
  - 2.2
  - 2.1

gemfile:
  - gemfiles/gemfile.rails42
  - gemfiles/gemfile.rails41

notifications:
  irc: "irc.freenode.org#projecthydra"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
