language: ruby
rvm:
  - 2.1

gemfile:
  - gemfiles/gemfile.rails4.1
  - gemfiles/gemfile.rails4.2

notifications:
  irc: "irc.freenode.org#projecthydra"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
